In [54]:
fullName =lambda Fname,Lname:f'{Fname} {Lname}' 
fullName("fatima","Musawi")

'fatima Musawi'

In [55]:
import numpy as np
array1=np.arange(0,11,1)
print(array1)
pyhton_list=[1,2,34,4]
array2=np.array(pyhton_list)
print (array2)
arr2d=np.array([[1,2,3],[4,5,6]])
print(arr2d,arr2d.shape)
listtemp=[1,2]
arr5d=np.array(listtemp,ndmin=5)
print(arr5d)
a=np.concatenate((array1,array2))


[ 0  1  2  3  4  5  6  7  8  9 10]
[ 1  2 34  4]
[[1 2 3]
 [4 5 6]] (2, 3)
[[[[[1 2]]]]]


In [56]:
import pandas as pd
createpdserias=pd.Series([1,2,np.nan,3])
print(createpdserias)
#pd date range
print(pd.date_range("08/01/2023","12/09/2023",freq="m"))
#print(pd.date_range("08/01/2023","12/09/2023",periods="6"))



0    1.0
1    2.0
2    NaN
3    3.0
dtype: float64
DatetimeIndex(['2023-08-31', '2023-09-30', '2023-10-31', '2023-11-30'], dtype='datetime64[ns]', freq='M')


In [ ]:
nparrayOfFruits=["banana",5,7],
                 ["apple",3,4],
                 [["strow",3,4]]
frutes=pd.DataFrame(npArrayOfData, index=“index column or
values”, columns=“List of column names”)
                 