# CSCN8000 – Artificial Intelligence Algorithms and Mathematics

## Lab 1, Liner Algebra

### Part A

**1-an array that starts from the integer 1, ends at 20, incremented by 3.**

In [257]:
import numpy as np
a=np.arange(1,20,3)
print (a)

[ 1  4  7 10 13 16 19]


**2-Creating a new array of shape 3 with random numbers between 0 and 1.**

In [258]:
a=np.random.rand(3)
print(a)

[0.3756595  0.47327965 0.12387546]


**3-Create a 2 D array [[10,20,45],[30,12,16],[42,17,56]] and perform the following operations
Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows:**

In [259]:
b=np.array([[10,20,45],[30,12,16],[42,17,56]] )
print (b[0:2,:])       #slicing to get first 2 rows
print (b[1:3,:])         #slicing to get first 2 rows


[[10 20 45]
 [30 12 16]]
[[30 12 16]
 [42 17 56]]


**4-Creating two 2x2 arrays and demonstrating to stack the elements vertically, horizontally, and split the arrays into smaller arrays.**

In [260]:
a=np.array([[1,2],[3,4]])
b=np.array([[4,5],[6,4]])
vertically_stack=np.vstack((a,b))
horizontally_stack=np.hstack((a,b))
print(vertically_stack)
print(horizontally_stack)
vertically_split=np.vsplit(vertically_stack,2)
horizontally_split=np.hsplit(horizontally_stack,2)
print(vertically_split)
print(horizontally_split)

[[1 2]
 [3 4]
 [4 5]
 [6 4]]
[[1 2 4 5]
 [3 4 6 4]]
[array([[1, 2],
       [3, 4]]), array([[4, 5],
       [6, 4]])]
[array([[1, 2],
       [3, 4]]), array([[4, 5],
       [6, 4]])]


**5:Multiply Matrices:**
for mutiply matrices the number of columns in the first matrix (X) should be equal to the number of rows in the second matrix(y). in this question x:(3,3) and y:(3,2).so Is it possible to multiply them

In [261]:
x= np.array([[5,7,2],[4,5,6],[7,4 ,2]])
y= np.array ([[4,2],[6,2],[4,2]])
print(x)
print(y)
z=np.dot(x,y)
print(z)

[[5 7 2]
 [4 5 6]
 [7 4 2]]
[[4 2]
 [6 2]
 [4 2]]
[[70 28]
 [70 30]
 [60 26]]


Example of matrices that can't be muliplied:

In [262]:
# x= np.array([[5,7,2],[4,5,6],[7,4 ,2]])
# y= np.array ([[4,2,4],[6,2,4],])
# print(x)
# print(y)
# z=np.dot(x,y)
# print(z)

In [4]:
import numpy as np
x1 =np.array([2,-1,-8])
y1 =np.array ([3,1,-2])

print("the shape of array x is: ",np.shape(x1))   
print("the dimention of vector x is: ",np.ndim(x1))  

 

the shape of array x is:  (3,)
the dimention of vector x is:  1


**Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).**

In [264]:
import numpy as np

x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

# Reshape x to a matrix of size (3,1)
x_reshaped = x.reshape((3, 1))

# Reshape y to a matrix of size (3,1)
y_reshaped = y.reshape((3, 1))

# Find the number of dimensions after reshaping
dimensions_x_reshaped = x_reshaped.ndim
dimensions_y_reshaped = y_reshaped.ndim

print("Reshaped x matrix:")
print(x_reshaped)
print("Number of dimensions after reshaping x:", dimensions_x_reshaped)

print("\nReshaped y matrix:")
print(y_reshaped)
print("Number of dimensions after reshaping y:", dimensions_y_reshaped)


Reshaped x matrix:
[[ 2]
 [-1]
 [-8]]
Number of dimensions after reshaping x: 2

Reshaped y matrix:
[[ 3]
 [ 1]
 [-2]]
Number of dimensions after reshaping y: 2


**7_How does broadcasting work?** broadcasting means the way that NumPy deals with arrays during operations.he smaller array is “broadcast” across the larger array so that they have compatible shapes.

In [265]:
x = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
multiplication_x=x* 2
subtraction_x=x-5
print(subtraction_x)
print(multiplication_x)

[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


### Part B- Linear Equations
**Part B.1**
the system below is nonsingular because:
1:if we calculate the determinant will *not* equal to zero
2: it does not have depended rows
so in this case we can find a solution and it is a nonsingular

In [266]:
A=np.array([[4,1,-2],[2,-3,2],[1,2,3]])
print(A)
b=np.array([10,-4,6])
G=np.linalg.solve(A,b)
print(G)

#to check if the solution is correct,we can try this code 
np.allclose(np.dot(A,x),b)

[[ 4  1 -2]
 [ 2 -3  2]
 [ 1  2  3]]
[ 1.8  2.4 -0.2]


False

**Part B- Linear Equations**
Part B.2:

the system below is singular because:
the first 2 rows are depended,so in this situation we know that there are no solution for these system.trying to sove this with numpy,will give us error as shown below:

In [267]:
S=np.array([[2,-1,3,4],[4,-2,6,8],[3,1,-2,2],[1,3,-4,1]])
print(S)
B=np.array([10,20,3,-1])
C=np.linalg.solve(S,B)
print(C)

[[ 2 -1  3  4]
 [ 4 -2  6  8]
 [ 3  1 -2  2]
 [ 1  3 -4  1]]


LinAlgError: Singular matrix